image: gitlab.pixl8.london:5005/utilities/pixl8-ci-env-docker-image
cache:
    paths:
        - tests/testbox/
        - assets/node_modules/

before_script:
  - box slack set defaults channel="team-elf-builds" title="Calendars Gitlab build ${CI_JOB_ID} (${CI_COMMIT_REF_NAME})" titleLink="${CI_PROJECT_URL}/builds/${CI_JOB_ID}" author="${GITLAB_USER_EMAIL}"

stages:
  - package

package:
    stage: package
    only:
      - /v[0-9].*/
      - /release\-\.*/
    script:
      - ./build.sh
      - aws s3 cp build/*.zip s3://pixl8-packages/calendar-view/
      - box slack send message color="good" message="Calendars ${CI_COMMIT_REF_NAME} package and build complete!"
